AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Private API with VPC Endpoint example

Parameters:
  Environment:
    Type: String
    Default: dev
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-093a5f04db74d3d38
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-0b2ed3cf13712f581
  VpceSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0ba217fefff2539bf

Resources:

  PrivateApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub my-private-api-${Environment}
      StageName: !Ref Environment
      EndpointConfiguration: 
        Type: PRIVATE
        VpcEndpointIds: 
        - vpce-0888b20905d6f59e5
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: "*"
              Action: execute-api:Invoke
              Resource: execute-api:/*/*/*
              Condition:
                StringEquals:
                  aws:SourceVpce: vpce-0888b20905d6f59e5


